version: '3.8'
services:
  movies:
    image: varalasumanth/paytmmovies:latest
    ports:
      - "81:80"
    deployment:
      replicas: 3
  train:
    image: varalasumanth/paytmtrain:latest
    ports:
      - "82:80"
    deployment:
      replicas: 3
  dth:
    image: varalasumanth/paytmdth:latest
    ports:
      - "83:80"
    deployment:
      replicas: 3
  recharge:
    image: varalasumanth/paytmrecharge:latest
    ports:
      - "84:80"
    deployment:
      replicas: 3
